# Generated by Django 4.1.7 on 2023-04-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='departmentss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='department',
        ),
    ]
