# Generated by Django 4.1.7 on 2023-05-11 06:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0003_docterdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=100)),
                ('PatientPhone', models.IntegerField()),
                ('PatientEmail', models.EmailField(max_length=254)),
                ('dateall', models.DateField(default=django.utils.timezone.now)),
                ('docname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new1.docterdetails')),
            ],
        ),
    ]
