# Generated by Django 4.1.7 on 2023-05-17 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new1', '0006_alter_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maindate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
